languageCode = "en-gb"
title = "generic test domain"
baseURL = "http://generictestdomain.net"
author = "Laurie Clark-Michalek"

publishDir = "."

[params]
 google_analytics_id = "UA-25243984-2"
 twitter_username = "lclarkmichalek"
